#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -s lineSample \
    postProcess -func line.sample -latestTime
runApplication -s cylinderSample \
    postProcess -func cylinder.sample -latestTime

hy2Foam -postProcess -dict 'system/surfaceCoefficients' -latestTime

#------------------------------------------------------------------------------
