#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.bak 0
runApplication blockMesh

# Create faceZone for baffle
runApplication -s baffle \
    topoSet -dict system/baffle.topoSetDict
# Create wall baffle and the fields on them
runApplication createBaffles -overwrite

# Refinement near the baffle
for i in 1 2 3
  do
    runApplication -s refineBaffle$i \
	topoSet -dict system/baffleRefinement/refine$i.topoSetDict
    runApplication -s refineBaffle$i \
	refineMesh -overwrite -dict system/baffleRefinement/refineMeshDict1
done

for i in 4 5
  do
    runApplication -s refineBaffle$i \
	topoSet -dict system/baffleRefinement/refine$i.topoSetDict
    runApplication -s refineBaffle$i \
	refineMesh -overwrite -dict system/baffleRefinement/refineMeshDict2
done

# Refinement near the shock wave
for i in 1
  do
    runApplication -s refineWave$i \
	topoSet -dict system/waveRefinement/refine$i.topoSetDict
    runApplication -s refineWave$i \
	refineMesh -overwrite -dict system/waveRefinement/refineMeshDict
done

runApplication renumberMesh

runApplication checkMesh

#------------------------------------------------------------------------------
